### ISSUE TITLE
FPGA Error

### ISSUE THREAD

**Issue by LightManager** [jelinj8/dso203#13]
Could you help me pls??? I tried to upgrade my DSO with 281_FPGA.BIN but now it write "FPGA Configuration Error". What  me do now? Wher can i get original FPGA config? Pls, help!

**Comment by f-alex** [comment]
Do you flash FPGA_281.ADR first?

**Comment by LightManager** [comment]
> Do you flash FPGA_281.ADR first?

Yes, did it. First time I flashed app1_a.adr, app1_a.bin, b and c parts of WildcatV6.5 like in description and had got  only first  screen without errors. Only descriptions about version, logo  screen, etc. But it didn't load to work state. So i flashed 281_FPGA, and had FPGA Config Error. I tried to repeat all these steps but the same result.

**Comment by MotoMaxis** [comment]
What hardware version is your DS203?

**Comment by LightManager** [comment]
> What hardware version is your DS203?

On screen it show 2.81, but where is label 2.82 inside on PCB.

**Comment by MotoMaxis** [comment]
Great, Download [RECOVERY281282.zip](https://github.com/MotoMaxis/DS203-DSOQuad/blob/master/RECOVERY281282.zip) 

Extract and flash 2 to 4, once its working then flash Wildcat 6.5.  

Finally you can flash custom fpga here, first .ADR then BIN https://github.com/MotoMaxis/DS203-DSOQuad/tree/master/WildcatV6.5/W1.1%20FPGA

**Comment by LightManager** [comment]
> Great, Download [RECOVERY281282.zip](https://github.com/MotoMaxis/DS203-DSOQuad/blob/master/RECOVERY281282.zip)
> 
> Extract and flash 2 to 4, once its working then flash Wildcat 6.5.
> 
> Finally you can flash custom fpga here, first .ADR then BIN https://github.com/MotoMaxis/DS203-DSOQuad/tree/master/WildcatV6.5/W1.1%20FPGA

I tried. APP.bin always get .ERR :( Enother files in this 3 folders flashed good. As additional I tried to flash LOGO.bin.  And it get .ERR  too. It's mystik, i dont  understand this.

**Comment by MotoMaxis** [comment]
Copy the .ADR first, then .Bin. If there is .HEX, copy it instead,

**Comment by LightManager** [comment]
> Copy the .ADR first, then .Bin. If there is .HEX, copy it instead,

Thsnk you so much for your answers! I had tied like you say but nothing - fpga error.
I put ds203SYS.hex - got .RDY. Next i put ds203APP.hex without reload - got .ERR. Every time. I reload ds203 and enter to DFU again, put ds203APP.hex - got .RDY. Put FPGA.ADR - got .SET. Put FPGA.bin - got.RDY.
I had tried reload ds203 between each folders - always without .ERR, but the same result - fpga error.
Is it OK what DS203.hex smaller than APP.bin? I had tried to flash APP.bin using APP.ADR but always - .ERR.

**Comment by MotoMaxis** [comment]
> I put ds203SYS.hex - got .RDY. Next i put ds203APP.hex without reload - got .ERR. Every time. I reload ds203 and enter to DFU again, put ds203APP.hex - got .RDY. Put FPGA.ADR - got .SET. Put FPGA.bin - got.RDY.

If you have done above than the DS203 should be working since you got RDY for SYS, APP and FPGA.  Does it boot normally?  If still FPGA config error than something is not flashing, either FPGA bin or APP.

I suggest you also try flash https://github.com/MotoMaxis/DS203-DSOQuad/blob/master/WildcatV6.5/app1.hex 

Does it boot?

**Comment by LightManager** [comment]
> If you have done above than the DS203 should be working since you got RDY for SYS, APP and FPGA. Does it boot normally? If still FPGA config error than something is not flashing, either FPGA bin or APP.
> 
> I suggest you also try flash https://github.com/MotoMaxis/DS203-DSOQuad/blob/master/WildcatV6.5/app1.hex
> 
> Does it boot?

No it doesn't :( Yes, I've got RDY for all 3 steps(and not once) but still have "fpga error'.
I tried to flash app1.hex from the beginning when I started flashing - It described as "Easy way". But I had a problem with download. The download was interrupted and the device rebooted. So I used "Hard way" and flashed with 4 parts(.ADDR and .bin). There was .RDY for all parts, and wasn't "fpga error", but device did't start - only first screen with logo and serial numbers, etc. Then I was flashed it with FPGA_281.ADR and 281_FPGA.bin, and from that moment on I always have "fpga error".

**Comment by LightManager** [comment]
I found a solution to my problem. I took the UART adapter and downloaded the DS dump. I compared the dump by addresses and found out that some areas of memory are not flashed correctly, as you said. Only the first few bytes match, and then either 0xFF or garbage. I flashed the DS203 using your dumps and now it works fine with Wildcat. Thank you for your answers and for this repository!
