### ISSUE TITLE
Code/buildability issue

### ISSUE THREAD

**Issue by ZHNNN** [jelinj8/dso203#6]
Hi,  I have built Wildcat's version using GCC 8.1.  I'm using Linux so I just ignored most of the instructions given with Wildcat's version.  The filesize is smaller than his using the newer compiler, and 6.5 seems to be working well enough on my device with HW 2.81 but I have only used a few features.  My device was previously bricked using the factory software save BMP function, so even if there is some error, it is still an upgrade.  

I see your version retains the following issue, which is at least a buildability issue using GCC with -Werror, and possibly also a code mistake:
The following line in Calibrat.c:
`if(Offset<-2)Offset=-2; if(Offset>2)Offset=2; Offset+=2;    //limit to +/- 2 steps`

Is it intentional that the value of variable 'Offset' is limited between 0 to 4?
It looks like `Offset+=2;` is not intended there.

I turned off -Werror while compiling as I did not have time to follow others through in that moment.

Apologies in advance if this is not the correct venue for this issue.  I have not worked on open source projects before.  If you find it helpful, I may be able to try your branch out with -Werror when I have some free time and sort out some simple syntax complaints from GCC at least.

I also offer some suggestions:
Providing a precompiled hex with the source may help many more people use a project like this.  Most people are not programmers.  Some programmers are like myself, lacking the expertise required to help much.

Including a full image, and a restore image, for each hardware version you have (can take with stm32flash) might not be a bad idea, since this can be sometimes challenging to find or poorly labeled.
I can provide you with a base image for HW 2.81 if you like, and if at a later date if I get your branch compiled and working, one with it installed.  User only needs 3.3v serial connection (such as 2€ arduino mini), and to first enter their license from a hex editor starting at 0xFC (little-endian/backwards).

**Comment by MarSoft** [comment]
Fixed this in PR #8

**Comment by jelinj8** [comment]
Thanks.
